version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 976193228213.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - docker build -t web-assignment .
      - docker tag web-assignment:latest 976193228213.dkr.ecr.ap-south-1.amazonaws.com/aws-assignment:latest
  post_build:
    commands:
      - docker push 976193228213.dkr.ecr.ap-south-1.amazonaws.com/aws-assignment:latest
