apiVersion: v1
kind: Service
metadata:
  name: web-assignment-service
spec:
  type: LoadBalancer
  selector:
    app: web-assignment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
